;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        comment-line-dwim
        forward-sentence
        isearch-forward-use-region
        kill-region
        move-text-up
        nxml-electric-slash
        nxml-finish-element
        open-line-above
        open-line-below
        perl-electric-terminator
        save-region-or-current-line
        shell
        yas-expand
        ))

(setq mc/cmds-to-run-once
      '(
        end-of-buffer
        ido-switch-buffer
        ignore
        isearch-backward-use-region
        mouse-minor-mode-menu
        open-line-and-indent
        org-self-insert-command
        overwrite-mode
        smex
        ))
