;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        backward-delete-char
        c-electric-colon
        c-electric-delete-forward
        c-electric-paren
        c-electric-semi&comma
        comment-line-dwim
        electric-newline-and-maybe-indent
        forward-sentence
        god-local-mode
        god-mode-all
        hippie-expand-no-case-fold
        isearch-forward-use-region
        kill-region
        move-text-up
        nxml-electric-slash
        nxml-finish-element
        open-line-above
        open-line-below
        perl-electric-terminator
        save-region-or-current-line
        shell
        sp--self-insert-command
        sp-forward-slurp-sexp
        yas-expand
        yas-next-field-or-maybe-expand
        ))

(setq mc/cmds-to-run-once
      '(
        end-of-buffer
        eshell-previous-matching-input-from-input
        god-mode-self-insert
        ido-switch-buffer
        ignore
        isearch-backward-use-region
        mouse-minor-mode-menu
        open-line-and-indent
        org-self-insert-command
        overwrite-mode
        smex
        ))
